export const surahList = [
  { number: 1, name: 'Al-Fatihah ', meaning: 'The Opening', imageUrl: '/Images/01.png' },
  { number: 2, name: 'Al-Baqarah ', meaning: 'The Cow', imageUrl: '/Images/02.png' },
  { number: 3, name: 'Al-Imran ', meaning: 'The Family of Imran', imageUrl: '/Images/03.png' },
  { number: 4, name: 'An-Nisa ', meaning: 'The Women', imageUrl: '/Images/04.png' },
  { number: 5, name: 'Al-Maidah ', meaning: 'The Table Spread with Food', imageUrl: '/Images/05.png' },
  { number: 6, name: 'Al-Anam ', meaning: 'The Cattle', imageUrl: '/Images/06.png' },
  { number: 7, name: 'Al-Araf ', meaning: 'The Wall with Elevations', imageUrl: '/Images/07.png' },
  { number: 8, name: 'Al-Anfal ', meaning: 'The Spoils of War', imageUrl: '/Images/08.png' },
  { number: 9, name: 'At-Taubah ', meaning: 'The Repentance', imageUrl: '/Images/09.png' },
  { number: 10, name: 'Yunus ', meaning: 'Jonah', imageUrl: '/Images/10.png' },
  { number: 11, name: 'Hud ', meaning: 'Hud', imageUrl: '/Images/11.png' },
  { number: 12, name: 'Yusuf ', meaning: 'Joseph', imageUrl: '/Images/12.png' },
  { number: 13, name: 'Ar-Rad ', meaning: 'The Thunder', imageUrl: '/Images/13.png' },
  { number: 14, name: 'Ibrahim ', meaning: 'Abraham', imageUrl: '/Images/14.png' },
  { number: 15, name: 'Al-Hijr ', meaning: 'The Rocky Tract', imageUrl: '/Images/15.png' },
  { number: 16, name: 'An-Nahl ', meaning: 'The Bee', imageUrl: '/Images/16.png' },
  { number: 17, name: 'Bani-Israel ', meaning: 'The Israelities', imageUrl: '/Images/17.png' },
  { number: 18, name: 'Al-Kahf ', meaning: 'The Cave', imageUrl: '/Images/18.png' },
  { number: 19, name: 'Maryam ', meaning: 'Mary', imageUrl: '/Images/19.png' },
  { number: 20, name: 'Ta-Ha ', meaning: '', imageUrl: '/Images/20.png' },
  { number: 21, name: 'Al-Anbiya ', meaning: 'The Prophets', imageUrl: '/Images/21.png' },
  { number: 22, name: 'Al-Hajj ', meaning: 'The Pilgrimage', imageUrl: '/Images/22.png' },
  { number: 23, name: 'Al-Muminun ', meaning: 'The Believers', imageUrl: '/Images/23.png' },
  { number: 24, name: 'An-Nur ', meaning: 'The Light', imageUrl: '/Images/24.png' },
  { number: 25, name: 'Al-Furqan ', meaning: 'The Criterion', imageUrl: '/Images/25.png' },
  { number: 26, name: 'Ash-Shuara ', meaning: 'The Poets', imageUrl: '/Images/26.png' },
  { number: 27, name: 'An-Naml ', meaning: 'The Ant', imageUrl: '/Images/27.png' },
  { number: 28, name: 'Al-Qasas', meaning: 'The Narration', imageUrl: '/Images/28.png' },
  { number: 29, name: 'Al-Ankabut', meaning: 'The Spider', imageUrl: '/Images/29.png' },
  { number: 30, name: 'Ar-Rum', meaning: 'The Romans', imageUrl: '/Images/30.png' },
  { number: 31, name: 'Luqman ', meaning: 'Luqman', imageUrl: '/Images/31.png' },
  { number: 32, name: 'As-Sajdah ', meaning: 'The Prostration', imageUrl: '/Images/32.png' },
  { number: 33, name: 'Al-Ahzab ', meaning: 'The Confederates', imageUrl: '/Images/33.png' },
  { number: 34, name: 'Al-Saba ', meaning: 'The Sheba', imageUrl: '/Images/34.png' },
  { number: 35, name: 'Al-Fatir ', meaning: 'The Originator', imageUrl: '/Images/35.png' },
  { number: 36, name: 'Ya-Sin ', meaning: '', imageUrl: '/Images/36.png' },
  { number: 37, name: 'As-Saffat ', meaning: 'Those Arranged in Ranks', imageUrl: '/Images/37.png' },
  { number: 38, name: 'Sad ', meaning: '', imageUrl: '/Images/38.png' },
  { number: 39, name: 'Az-Zumar ', meaning: 'The Troops', imageUrl: '/Images/39.png' },
  { number: 40, name: 'Al-Mumin ', meaning: 'The Believer', imageUrl: '/Images/40.png' },
  { number: 41, name: 'Ha-Mim ', meaning: '', imageUrl: '/Images/41.png' },
  { number: 42, name: 'Ash-Shura ', meaning: 'The Consultation', imageUrl: '/Images/42.png' },
  { number: 43, name: 'Az-Zukhruf ', meaning: 'The Gold', imageUrl: '/Images/43.png' },
  { number: 44, name: 'Ad-Dukhan ', meaning: 'The Smoke', imageUrl: '/Images/44.png' },
  { number: 45, name: 'Al-Jathiyah ', meaning: 'The Kneeling', imageUrl: '/Images/45.png' },
  { number: 46, name: 'Al-Ahqaf ', meaning: 'The Curved Sandhills', imageUrl: '/Images/46.png' },
  { number: 47, name: 'Muhammad', meaning: 'Muhammad', imageUrl: '/Images/47.png' },
  { number: 48, name: 'Al-Fath', meaning: 'The Victory', imageUrl: '/Images/48.png' },
  { number: 49, name: 'Al-Hujurat', meaning: 'The Rooms', imageUrl: '/Images/49.png' },
  { number: 50, name: 'Qaf', meaning: '', imageUrl: '/Images/50.png' },
  { number: 51, name: 'Ad-Dhariyat', meaning: 'The Wind that Scatters', imageUrl: '/Images/51.png' },
  { number: 52, name: 'At-Tur', meaning: 'The Mountain', imageUrl: '/Images/52.png' },
  { number: 53, name: 'An-Najm', meaning: 'The Star', imageUrl: '/Images/53.png' },
  { number: 54, name: 'Al-Qamar', meaning: 'The Moon', imageUrl: '/Images/54.png' },
  { number: 55, name: 'Ar-Rahman', meaning: 'The Most Gracious', imageUrl: '/Images/55.png' },
  { number: 56, name: 'Al-Waqiyah', meaning: 'The Event', imageUrl: '/Images/56.png' },
  { number: 57, name: 'Al-Hadid', meaning: 'Iron', imageUrl: '/Images/57.png' },
  { number: 58, name: 'Al-Mujadilah', meaning: 'The Pleading Woman', imageUrl: '/Images/58.png' },
  { number: 59, name: 'Al-Hashr', meaning: 'The Banishment', imageUrl: '/Images/59.png' },
  { number: 60, name: 'Al-Mumtahanah', meaning: 'The Woman to be Examined', imageUrl: '/Images/60.png' },
  { number: 61, name: 'As-Saff', meaning: 'The Ranks', imageUrl: '/Images/61.png' },
  { number: 62, name: 'Al-Jumuah', meaning: 'The Friday Congregation', imageUrl: '/Images/62.png' },
  { number: 63, name: 'Al-Munafiqun', meaning: 'The Hypocrites', imageUrl: '/Images/63.png' },
  { number: 64, name: 'At-Taghabun', meaning: 'The Mutual Loss or Gain', imageUrl: '/Images/64.png' },
  { number: 65, name: 'At-Talaq', meaning: 'The Divorce', imageUrl: '/Images/65.png' },
  { number: 66, name: 'At-Tahrim', meaning: 'The Prohibition', imageUrl: '/Images/66.png' },
  { number: 67, name: 'Al-Mulk', meaning: 'The Sovereignty', imageUrl: '/Images/67.png' },
  { number: 68, name: 'Al-Qalam', meaning: 'The Pen', imageUrl: '/Images/68.png' },
  { number: 69, name: 'Al-Haqqah', meaning:'The Inevitable', imageUrl: '/Images/69.png' },
  { number: 70, name: 'Al-Maarij', meaning: 'The Ways of Ascent', imageUrl: '/Images/70.png' },
  { number: 71, name: 'Nuh', meaning: 'Noah', imageUrl: '/Images/71.png' },
  { number: 72, name: 'Al-Jinn', meaning: 'The Jinn', imageUrl: '/Images/72.png' },
  { number: 73, name: 'Al-Mujjammil', meaning: 'The One Covering Himself', imageUrl: '/Images/73.png' },
  { number: 74, name: 'Al-Muddaththir', meaning: 'The One Wrapping Himself', imageUrl: '/Images/74.png' },
  { number: 75, name: 'Al-Qiyamah', meaning: 'The Resurrection', imageUrl: '/Images/75.png' },
  { number: 76, name: 'Al-Insan', meaning: 'The Man', imageUrl: '/Images/76.png' },
  { number: 77, name: 'Al-Mursalat', meaning: 'Those Sent Forth', imageUrl: '/Images/77.png' },
  { number: 78, name: 'An-Naba', meaning: 'The Announcement', imageUrl: '/Images/78.png' },
  { number: 79, name: 'An-Naziat', meaning: 'Those Who Yearn', imageUrl: '/Images/79.png' },
  { number: 80, name: 'Abasa', meaning: 'He Frowned', imageUrl: '/Images/80.png' },
  { number: 81, name: 'At-Takwir', meaning: 'The Folding Up', imageUrl: '/Images/81.png' },
  { number: 82, name: 'Al-Infitar', meaning: 'The Cleaving', imageUrl: '/Images/82.png' },
  { number: 83, name: 'At-Tatfif', meaning: 'Default in Duty', imageUrl: '/Images/83.png' },
  { number: 84, name: 'Al-Inshiqaq', meaning: 'The Bursting Asunder', imageUrl: '/Images/84.png' },
  { number: 85, name: 'Al-Buruj', meaning: 'The Mansions of the Stars', imageUrl: '/Images/85.png' },
  { number: 86, name: 'At-Tariq', meaning: 'The Comer by Night', imageUrl: '/Images/86.png' },
  { number: 87, name: 'Al-Ala', meaning: 'The Most High', imageUrl: '/Images/87.png' },
  { number: 88, name: 'Al-Ghashiyah', meaning: 'The Overwhelming Event', imageUrl: '/Images/88.png' },
  { number: 89, name: 'Al-Fajr', meaning: 'The Dawn', imageUrl: '/Images/89.png' },
  { number: 90, name: 'Al-Balad', meaning: 'The City', imageUrl: '/Images/90.png' },
  { number: 91, name: 'Ash-Shams', meaning:'The Sun', imageUrl: '/Images/91.png' },
  { number: 92, name: 'Al-Lail', meaning:'The Night', imageUrl: '/Images/92.png' },
  { number: 93, name: 'Ad-Duha', meaning: 'The Brightness of the Day', imageUrl: '/Images/93.png' },
  { number: 94, name: 'Al-Inshirah', meaning: 'The Expansion', imageUrl: '/Images/94.png' },
  { number: 95, name: 'At-Tin', meaning: 'The Fig', imageUrl: '/Images/95.png' },
  { number: 96, name: 'Al-Alaq', meaning: 'The Clot', imageUrl: '/Images/96.png' },
  { number: 97, name: 'Al-Qadar', meaning: 'The Majesty', imageUrl: '/Images/97.png' },
  { number: 98, name: 'Al-Bayyinah', meaning: 'The Clear Evidence', imageUrl: '/Images/98.png' },
  { number: 99, name: 'Al-Zilzal', meaning: 'The Shaking', imageUrl: '/Images/99.png' },
  { number: 100, name: 'Al-Adiyat', meaning: 'The Assaulters', imageUrl: '/Images/100.png' },
  { number: 101, name: 'Al-Qariah', meaning: 'The Calamity', imageUrl: '/Images/101.png' },
  { number: 102, name: 'At-Takathur', meaning: 'The Abundance of Wealth', imageUrl: '/Images/102.png' },
  { number: 103, name: 'Al-Asr', meaning: 'The Time', imageUrl: '/Images/103.png' },
  { number: 104, name: 'Al-Humazah', meaning: 'The Slanderer', imageUrl: '/Images/104.png' },
  { number: 105, name: 'Al-Fil', meaning: 'The Elephant', imageUrl: '/Images/105.png' },
  { number: 106, name: 'Al-Quraish', meaning: 'The Quraish', imageUrl: '/Images/106.png' },
  { number: 107, name: 'Al-Maun', meaning: 'The Acts of Kindness', imageUrl: '/Images/107.png' },
  { number: 108, name: 'Al-Kauthar', meaning: 'The Abundance of Good', imageUrl: '/Images/108.png' },
  { number: 109, name: 'Al-Kafirun', meaning: 'The Disbelievers', imageUrl: '/Images/109.png' },
  { number: 110, name: 'An-Nasr', meaning: 'The Help', imageUrl: '/Images/110.png' },
  { number: 111, name: 'Al-Lahab', meaning: 'The Flame', imageUrl: '/Images/111.png' },
  { number: 112, name: 'Al-Ikhlas', meaning: 'The Sincerity', imageUrl: '/Images/112.png' },
  { number: 113, name: 'Al-Falaq', meaning: 'The Dawn', imageUrl: '/Images/113.png' },
  { number: 114, name: 'An-Nas', meaning: 'The Men', imageUrl: '/Images/114.png' }
];
